src/accs/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "accs"

urlpatterns = [ 
    path("login/", views.MyLoginView.as_view(), name="login"),
    path("logout/", views.MyLogoutView.as_view(), name="logout"),
    path("pass_change/", views.MyPasswordChangeView.as_view(), name="pass_change"),
    path("pass_change_done/", views.MyPasswordChangeDoneView.as_view(), name="pass_change_done"),
    path("pass_reset/", views.MyPasswordResetView.as_view(), name="pass_reset"),
    path("pass_reset_done/", views.MyPasswordResetDoneView.as_view(), name="pass_reset_done"),
    path("pass_reset_confirm/", views.MyPasswordResetConfirmView.as_view(), name="pass_reset_confirm"),
    path("pass_reset_complete/", views.MyPasswordResetCompleteView.as_view(), name="pass_reset_complete"),



] 

if not settings.IS_PRODUCTION:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from directories import views as directories_views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('applications/', include("applications.urls")),
    path('directories/', include("directories.urls")),
    path('', directories_views.book_types, name="home"),
    path('orders/', include("orders.urls")),
    path('random_number/', include("random_number.urls")),
    path('accs/', include("accs.urls")),
] 

if not settings.IS_PRODUCTION:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accs/models.py
from django.db import models

# Create your models here.

src/accs/views.py
from django.shortcuts import render
from django.contrib.auth import views as auth_views
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# Create your views here.

class MyLoginView(auth_views.LoginView):
    template_name = "accs/login.html"

class MyLogoutView(auth_views.LogoutView):
    template_name = "accs/logout.html"

class MyPasswordChangeView(auth_views.PasswordChangeView):
    template_name = "registration/password_change_form.html"

class MyPasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    template_name = "registration/password_change_done.html"

class MyPasswordResetView(auth_views.PasswordResetView):
    template_name = "registration/password_reset_form.html"

class MyPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = "registration/password_reset_done.html"

class MyPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = "registration/password_reset_confirm.html"

class MyPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = "registration/password_reset_complete.html"

src/accs/templates/accs/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'accs:login' %}">
    {% csrf_token %}
    {{ form | crispy }}

<input type="submit" class="btn btn-outline-primary" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you set up the password_reset view in your URLconf #}
<p><a href="{% url 'accs:pass_reset' %}">Lost password?</a></p>

{% endblock body %}

src/accs/templates/accs/logout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body %}
<br>
<br>
<h2>You have logged out successfully!</h2>

{% endblock %}