src/accs/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "accs"

urlpatterns = [ 
    path("login/", views.MyLoginView.as_view(), name="login"),
    path("logout/", views.MyLogoutView.as_view(), name="logout"),
    path("pass_change/", views.MyPasswordChangeView.as_view(), name="pass_change"),
    path("pass_change_done/", views.MyPasswordChangeDoneView.as_view(), name="pass_change_done"),
    path("pass_reset/", views.MyPasswordResetView.as_view(), name="pass_reset"),
    path("pass_reset_done/", views.MyPasswordResetDoneView.as_view(), name="pass_reset_done"),
    path("pass_reset_confirm/", views.MyPasswordResetConfirmView.as_view(), name="pass_reset_confirm"),
    path("pass_reset_complete/", views.MyPasswordResetCompleteView.as_view(), name="pass_reset_complete"),



] 

if not settings.IS_PRODUCTION:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/directories/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "directories" 
# для bookname, genre, author сделаны постоянные ссылки в html

urlpatterns = [ 

    path('currency/<int:pk>/', views.CurrencyDetail.as_view(), name="currency_detail"),
    path('currency/update/<int:pk>/', views.CurrencyUpdate.as_view(), name="currency_update"),
    path('currency/', views.CurrencyList.as_view(), name="currency_list"),
    path('currency/create/', views.CurrencyCreate.as_view, name="currency_create"),
    path('currency/delete/<int:pk>/', views.CurrencyDelete.as_view(), name="currency_delete"),

    path('author/<int:pk>/', views.AuthorDetail.as_view(), name="author_detail"),
    path('author/update/<int:pk>/', views.AuthorUpdate.as_view(), name="author_update"),
    path('author/', views.AuthorList.as_view(), name="author_list"),
    path('author/create/', views.AuthorCreate.as_view(), name="author_create"),
    path('author/delete/<int:pk>/', views.AuthorDelete.as_view(), name="author_delete"),

    path('series/<int:pk>/', views.SeriesDetail.as_view(), name="series_detail"),
    path('series/update/<int:pk>/', views.SeriesUpdate.as_view(), name="series_update"),
    path('series/', views.SeriesList.as_view(), name="series_list"),
    path('series/create/', views.SeriesCreate.as_view(), name="series_create"),
    path('series/delete/<int:pk>/', views.SeriesDelete.as_view(), name="series_delete"),

    path('bookname/<int:pk>/', views.BookNameDetail.as_view(), name="bookname_detail"),
    path('bookname/update/<int:pk>/', views.BookNameUpdate.as_view(), name="bookname_update"),
    path('bookname/', views.BookNameList.as_view(), name="bookname_list"),
    path('bookname/create/', views.BookNameCreate.as_view(), name="bookname_create"),
    path('bookname/delete/<int:pk>/', views.BookNameDelete.as_view(), name="bookname_delete"),

    path('booktype/<int:pk>/', views.BookTypeDetail.as_view(), name="booktype_detail"),
    path('booktype/update/<int:pk>/', views.BookTypeUpdate.as_view(), name="booktype_update"),
    path('booktype/', views.BookTypeList.as_view(), name="booktype_list"),
    path('booktype/create/', views.BookTypeCreate.as_view(), name="booktype_create"),
    path('booktype/delete/<int:pk>/', views.BookTypeDelete.as_view(), name="booktype_delete"),


    path('rating/<int:pk>/', views.RatingDetail.as_view(), name="rating_detail"),
    path('rating/update/<int:pk>/', views.RatingUpdate.as_view(), name="rating_update"),
    path('rating/', views.RatingList.as_view(), name="rating_list"),
    path('rating/create/', views.RatingCreate.as_view(), name="rating_create"),
    path('rating/delete/<int:pk>/', views.RatingDelete.as_view(), name="rating_delete"),

    path('agelimit/<int:pk>/', views.AgeLimitDetail.as_view(), name="agelimit_detail"),
    path('agelimit/update/<int:pk>/', views.AgeLimitUpdate.as_view(), name="agelimit_update"),
    path('agelimit/', views.AgeLimitList.as_view(), name="agelimit_list"),
    path('agelimit/create/', views.AgeLimitCreate.as_view(), name="agelimit_create"),
    path('agelimit/delete/<int:pk>/', views.AgeLimitDelete.as_view(), name="agelimit_delete"),

    path('genre/<int:pk>/', views.GenreDetail.as_view(), name="genre_detail"),
    path('genre/update/<int:pk>/', views.GenreUpdate.as_view(), name="genre_update"),
    path('genre/', views.GenreList.as_view(), name="genre_list"),
    path('genre/create/', views.GenreCreate.as_view(), name="genre_create"),
    path('genre/delete/<int:pk>/', views.GenreDelete.as_view(), name="genre_delete"),
    
    path('copyrightholder/<int:pk>/', views.CopyrightHolderDetail.as_view(), name="copyrightholder_detail"),
    path('copyrightholder/update/<int:pk>/', views.CopyrightHolderUpdate.as_view(), name="copyrightholder_update"),
    path('copyrightholder/', views.CopyrightHolderList.as_view(), name="copyrightholder_list"),
    path('copyrightholder/create/', views.CopyrightHolderCreate.as_view(), name="copyrightholder_create"),
    path('copyrightholder/delete/<int:pk>/', views.CopyrightHolderDelete.as_view(), name="copyrightholder_delete"),
    
    #path('search', views.Search.as_view(), name="search"),
    
    ] 

if not settings.IS_PRODUCTION:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

src/orders/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from orders import views as views
from random_number import views as random_number_views
from django.conf.urls.static import static
from django.conf import settings

app_name = "orders" 

urlpatterns = [ 

    path('cart/', views.cart, name = "order_cart"),
    path('cart/<int:pk>/', views.Cart.as_view(), name = "order_cart_pk"),
    path('cart-delete-good/<int:pk>', views.DeleteGoodInCart.as_view(), name = "good_in_cart_delete"),
    path('order_success/', views.order_success, name = "order_success"),
    path('order_data/', views.OrderCreate.as_view(), name = "order_data"),
    path('order_list/', views.OrderList.as_view(), name = "order_list"),
    path("portal_main/", views.portal_view, name="portal_main"),
    path('portal_order/delete/<int:pk>/', views.OrderDelete.as_view(), name="portal_order_delete"),
    path('portal_order/update/<int:pk>/', views.OrderUpdate.as_view(), name="portal_order_update"),
    # path('order_empty/', views.order_success, name = "order_empty"),

] 

if not settings.IS_PRODUCTION:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from directories import views as directories_views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('applications/', include("applications.urls")),
    path('directories/', include("directories.urls")),
    path('', directories_views.book_types, name="home"),
    path('orders/', include("orders.urls")),
    path('random_number/', include("random_number.urls")),
    path('accs/', include("accs.urls")),
] 

if not settings.IS_PRODUCTION:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/models.py
from django.db import models
from directories.models import BookName
from django.db.models import Sum
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Cart(models.Model):
    customer = models.ForeignKey(
        User,
        verbose_name="Customer", 
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )

    created = models.DateTimeField(
        verbose_name="Created date",
        auto_now=False, 
        auto_now_add=True,
    )

    def __str__(self):
        return f"cart {self.pk}" 
    
    @property
    def good_quantity(self):
        return self.goods.aggregate(total=Sum("quantity")).get("total", 0)
    
    @property
    def total_price(self):
        summ = 0
        for good_in_cart in self.goods.all():
            summ += good_in_cart.total_price
        return summ
    

class GoodInCart(models.Model):
    cart = models.ForeignKey(
        Cart,
        verbose_name="Cart",
        on_delete=models.CASCADE,
        related_name="goods",
    )

    good = models.ForeignKey(
        BookName,
        verbose_name="Good",
        on_delete=models.PROTECT,
        related_name="carts", 
    )

    quantity = models.PositiveIntegerField(
        verbose_name="Quantity",
        default=1,
    )

    def __str__(self):
        return f"Good: {self.good.name}, quantity: {self.quantity}"
    
    @property
    def price(self):
        return self.good.price
    
    @property
    def total_price(self):
        return self.quantity * self.good.price
    

class Order(models.Model):
    cart = models.OneToOneField(
        Cart,
        verbose_name="Cart",
        on_delete=models.PROTECT,
        related_name="user_carts",
        blank=False,
        null=True, 
    )


    delivery_adress=models.TextField(
        verbose_name="Delivery adress",

    )

    email=models.EmailField(
        verbose_name="Email adress",

    )

    telephone_number=models.PositiveIntegerField(
        verbose_name="Telephone number", 
        
    ) 

    def get_absolute_url(self):
        return f"/orders/order_success/"

src/orders/forms.py
from django import forms
from django.core.exceptions import ValidationError 
from . import models

class SearchForm(forms.Form):
    query = forms.CharField()

class OrderModelForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = [
            'cart',
            'delivery_adress',
            'email',
            'telephone_number',
        ]

class CartModelForm(forms.ModelForm):
    class Meta:
        model = models.Cart
        fields = [
            'customer',
            
        ]

src/orders/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import UpdateView, DeleteView
from . import models, forms
from directories import models as good_model 
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

def update_cart(request):
    cart = None
    # cart = models.Cart.objects.create(
    # customer = request.user
    cart_id = request.session.get("cart_id")
    quantity = request.GET.get("quantity")
    good_pk = request.GET.get("good")
    action = request.GET.get("action")
    if quantity and good_pk:
        user = request.user
        if request.user.is_anonymous:
            user = None
        cart, created = models.Cart.objects.get_or_create(
            pk=cart_id, 
            defaults={
                "customer": user
            }
        )   

        if created:
            request.session["cart_id"] = cart.pk

        good = good_model.BookName.objects.get(pk=int(good_pk))
        good_in_cart, created = models.GoodInCart.objects.get_or_create( 
            cart=cart,
            good=good,
            defaults={
                "quantity": int(quantity),

            }
        )

        if not created:
            if action == "edit":
                good_in_cart.quantity = int(quantity)
            else:
                good_in_cart.quantity = good_in_cart.quantity + int(quantity)
                good_in_cart.save()
            if good_in_cart.quantity <= 0:
                good_in_cart.delete()
            else:
                good_in_cart.save()

    else:
        cart = models.Cart.objects.filter(pk=cart_id)
        if cart:
            cart = cart[0]
    return cart



def cart(request):
    cart = update_cart(request)
    return render(
        request=request,
        template_name="orders/cart.html",
        context={"cart": cart},

    )

# def cart_upd(self, pk, *args, **kwargs):
#     pk = pk
#     cart = update_cart(pk) 
#     return render(
#         template_name="orders/cart.html",
#         context={"cart": cart},

#     )
    
class Cart(LoginRequiredMixin, generic.UpdateView):
    template_name="orders/cart.html"
    login_url = "/admin/login/"
    model = models.Cart
    form_class = forms.OrderModelForm
    success_url = "/orders/order_list/"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["verb"] = "update"
        return context
    
class CartUpdate(LoginRequiredMixin, generic.UpdateView):
    template_name="orders/cart_update.html"
    login_url = "/admin/login/"
    model = models.Cart
    form_class = forms.OrderModelForm
    success_url = "/orders/order_list/"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["verb"] = "update"
        return context
    

class DeleteGoodInCart(DeleteView):
    model = models.GoodInCart
    success_url = "/orders/cart"


# def ordered_cart(request):
#     cart = update_cart(request)
#     return render(
#         request=request,
#         template_name="orders/order.html",
#         context={"cart": cart},

#     )

def order_success(request):
    cart_id = request.session.get("cart_id")
    if cart_id == None:
        return render(
            request=request,
            template_name="orders/order_empty.html",
        )
    
    else:
        del request.session["cart_id"]
        return render(
            request=request,
            template_name="orders/order_success.html",
        
        )
    
class OrderCreate(generic.CreateView):
    template_name="orders/order_data.html"
    model = models.Order
    form_class = forms.OrderModelForm

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["verb"] = "detail"
        cart_id = self.request.session.get("cart_id")
        context["cart_id"] = cart_id
        cart = models.Cart.objects.get(
            pk=cart_id
        )   
        context["cart"] = cart
        return context
    
    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(*args, **kwargs)
        cart_id = self.request.session.get("cart_id")
        cart = models.Cart.objects.get(
            pk=cart_id
        )   
        initial['cart'] = cart
        return initial
    

class OrderList(LoginRequiredMixin, generic.ListView):
    template_name="orders/portal_order_list.html"
    login_url = "/admin/login/"
    model = models.Order
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["verb"] = "list"
        return context
    
class OrderDelete(LoginRequiredMixin, generic.DeleteView):
    template_name="orders/portal_order_delete.html"
    model = models.Order
    login_url = "/admin/login/"
    success_url = "/orders/order_list/" 

class OrderUpdate(LoginRequiredMixin, generic.UpdateView):
    template_name="orders/portal_order_update.html"
    model = models.Order
    login_url = "/admin/login/"
    form_class = forms.OrderModelForm
    success_url = "/orders/order_list/" 

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["verb"] = "detail"
        return context
    

def portal_view(request):
    return render(
        request=request,
        template_name = "orders/portal_main.html",
        )



# from .forms import EmailPostForm, CommentForm, SearchForm
# from haystack.query import SearchQuerySet

# def post_search(request):
#     form = SearchForm()
    # if 'query' in request.GET:
    #     form = SearchForm(request.GET)
    #     if form.is_valid():
    #         cd = form.cleaned_data
    #         results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
    #         # count total results
    #         total_results = results.count()
    # return render(request,
    #               'blog/post/search.html',
    #               {'form': form,
    #                'cd': cd,
    #                'results': results,
    #                'total_results': total_results})

src/orders/templates/orders/cart.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Cart {{ verb }} {% endblock title %}
{% block body %}
    <h3>Cart</h3>
    <table class="table table-striped">
        <tr>
            <td>Book</td>
            <td>Quantity</td>
            <td>Price</td>
            <td>Total price</td>
            <td>Actions</td>
        </tr>
        {% for good_in_cart in cart.goods.all %}
        <tr>
            <td>{{ good_in_cart.good.name }}</td > 
            <td><form action="{% url 'orders:order_cart' %}">
                    <div class="input-group mb-1">
                        <input class="form-control" type="number" name="quantity" min="0" step="1" value="{{ good_in_cart.quantity }}">
                        <button type="submit" class="btn btn-outline-secondary">Ok</button>
                    </div>
                    <input type="hidden" name="good" value="{{ good_in_cart.good.pk }}">
                    <input type="hidden" name="action" value="edit">
        
                </form>
            </td>
            </td> 
            <td>{{ good_in_cart.price }}</td>
            <td>{{ good_in_cart.total_price }}</td>
            <td>
                <form action="{% url 'orders:good_in_cart_delete' good_in_cart.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger"><i class="bi bi-trash3-fill"></i></button>
                </form> 
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td>Total:</td>
            <td colspan="2">{{ cart.good_quantity }}</td>
            <td colspan="2">{{ cart.total_price }}</td>
        </tr>
    </table>
        <a href="{% url 'directories:bookname_list' %}" class="btn btn-outline-primary"><i class="bi bi-book"></i></a>
        <a href="{% url 'orders:order_data' %}" class="btn btn-outline-success"><i class="bi bi-check-square"></i></a>



{% endblock body %}

src/orders/templates/orders/cart_update.html
{% load crispy_forms_tags %}
{% block title %} Cart {{ verb }} {% endblock title %}
{% block body %}
    <h3>Cart cart cart</h3>
    <table class="table table-striped">
        <tr>
            <td>Book</td>
            <td>Quantity</td>
            <td>Price</td>
            <td>Total price</td>
            <td>Actions</td>
        </tr>
        {% for good_in_cart in cart.goods.all %}
        <tr>
            <td>{{ good_in_cart.good.name }}</td > 
            <td><form action="{% url 'orders:order_cart_pk' cart.pk %}" method="post">
                {% csrf_token %}
                    <div class="input-group mb-1">
                        <input class="form-control" type="number" name="quantity" min="0" step="1" value="{{ good_in_cart.quantity }}">
                        <button type="submit" class="btn btn-outline-secondary">Ok</button>
                    </div>
                    <input type="hidden" name="good" value="{{ good_in_cart.good.pk }}">
                    <input type="hidden" name="action" value="edit">
        
                </form>
            </td>
            </td> 
            <td>{{ good_in_cart.price }}</td>
            <td>{{ good_in_cart.total_price }}</td>
            <td>
                <form action="{% url 'orders:good_in_cart_delete' good_in_cart.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger"><i class="bi bi-trash3-fill"></i></button>
                </form> 
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td>Total:</td>
            <td colspan="2">{{ cart.good_quantity }}</td>
            <td colspan="2">{{ cart.total_price }}</td>
        </tr>
    </table>
        <a href="{% url 'directories:bookname_list' %}" class="btn btn-outline-primary"><i class="bi bi-book"></i></a>
        
        <form action="{% url 'orders:order_list' %}" >
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger"><i class="bi bi-trash3-fill"></i></button>
        </form> 
        


{% endblock body %}

src/orders/templates/orders/order_data.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Order {{ verb }} {% endblock title %}
{% block body %}
    <h3>Cart #{{ cart_id }} details</h3>

    <table class="table table-striped">
        <tr>
            <td>Book</td>
            <td>Quantity</td>
            <td>Price</td>
            <td>Total price</td>
        </tr>
        {% for good_in_cart in cart.goods.all %}
        <tr>
            <td>{{ good_in_cart.good.name }}</td > 
            <td>{{ good_in_cart.quantity }}</td>
            <td>{{ good_in_cart.price }}</td>
            <td>{{ good_in_cart.total_price }}</td>
        </tr>
        {% endfor %}
        <tr>
            <td>Total:</td>
            <td>{{ cart.good_quantity }}</td>
            <td></td>
            <td>{{ cart.total_price }}</td>
        </tr>
    </table>
    <br>

    <tr>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="cart_id" value="{{cart_id}}" />
            {{ form | crispy }}
            <a href="{% url 'directories:bookname_list' %}" class="btn btn-outline-primary"><i class="bi bi-book"></i></a>
            <button type="submit" class="btn btn-outline-success"><i class="bi bi-truck"></i></button>
        </form> 
    </tr>
    <br>


    {% for good_in_cart in cart.user_carts.all %}
        <tr>
            <td>{{ good_in_cart.user_carts.pk }}</td > 
            <td>{{ good_in_cart.user_carts.name }}</td>
        </tr>
        {% endfor %}


{% endblock body %}

src/orders/templates/orders/order_empty.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Order {{ verb }} {% endblock title %}
{% block body %}
    <h4>Sorry, but this cart is empty ;(</h4>
    <br>
    <h5>Please add some books to the сart</h5>
    <br>





        <a href="{% url 'directories:bookname_list' %}" class="btn btn-outline-primary"><i class="bi bi-book"></i></a>


{% endblock body %}

src/orders/templates/orders/portal_main.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load my_custom_tags %}

{% block body %}

{% if perms.auth.add_group %}
<div class="container px-4 py-5" id="featured-3">
    <h2 class="pb-2 border-bottom">Hello, {{user}}!</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <div class="feature col">

        <h3 class="fs-2 text-body-emphasis">Orders</h3>
        <a href="{% url 'orders:order_list' %}" class="icon-link">
          Go to the orders
          <svg class="bi"><use xlink:href="#chevron-right"/></svg>
        </a>
      </div>

    </div>

    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="feature col">

          <h3 class="fs-2 text-body-emphasis">Copyright holders</h3>
          <a href="{% url 'directories:copyrightholder_list' %}" class="icon-link">
            Go to the copyright holders
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
        <div class="feature col">
         
          <h3 class="fs-2 text-body-emphasis">Currencies</h3>
          <a href="{% url 'directories:currency_list' %}" class="icon-link">
            Go to the currencies
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
        <div class="feature col">
          
          <h3 class="fs-2 text-body-emphasis">Series</h3>
          <a href="{% url 'directories:series_list' %}" class="icon-link">
            Go to the series
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
      </div>

    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="feature col">

          <h3 class="fs-2 text-body-emphasis">Book's names</h3>
          <a href="{% url 'directories:bookname_list' %}" class="icon-link">
            Go to the book's names
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
        <div class="feature col">
         
          <h3 class="fs-2 text-body-emphasis">Authors</h3>
          <a href="{% url 'directories:author_list' %}" class="icon-link">
            Go to the authors
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
        <div class="feature col">
          
          <h3 class="fs-2 text-body-emphasis">Genres</h3>
          <a href="{% url 'directories:genre_list' %}" class="icon-link">
            Go to the genres
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
        
      </div>

    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="feature col">

          <h3 class="fs-2 text-body-emphasis">Book types</h3>
          <a href="{% url 'directories:booktype_list' %}" class="icon-link">
            Go to the book types
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
        <div class="feature col">
         
          <h3 class="fs-2 text-body-emphasis">Rating</h3>
          <a href="{% url 'directories:rating_list' %}" class="icon-link">
            Go to the rating
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
        <div class="feature col">
    
          <h3 class="fs-2 text-body-emphasis">Age limits</h3>
          <a href="{% url 'directories:agelimit_list' %}" class="icon-link">
            Go to the age limits
            <svg class="bi"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
      </div>

     

  </div>





{% endif %}
{% endblock body %}

src/orders/templates/orders/portal_order_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Orders's {{ verb }} {% endblock title %}
{% load my_custom_tags %}

{% block body %}

{% if perms.auth.add_group %}

<table class="table table-striped">
  <tr>
      <td>Order ID</td>
      <td>Cart ID</td>
      <td>User name</td>
      <td>Delivery adress</td>
      <td>Email adress</td>
      <td>Telephone</td>
      <td>Total price</td>
      <td>Actions</td>
  </tr>
  
  {% for object in object_list %}
  <tr>
      <!-- добавляем постоянные ссылки -->
      <td><a href="{% url 'orders:portal_order_update' object.pk %}" class="btn btn-outline-primary">{{ object.pk }}</a></td>
      <td><a href="/orders/cart/{{ object.cart.pk }}" class="btn btn-outline-primary">{{ object.cart.pk }}</a></td>
      <td>{{ object.cart.customer }}</td>
      <td>{{ object.delivery_adress }}</td>
      <td>{{ object.email }}</td>
      <td>{{ object.telephone_number }}</td>
      <td>{{ object.cart.total_price }}</td>

      <td>
          {% if perms.auth.add_group %}
          <!-- добавляем постоянные ссылки -->
          <a href="{% url 'orders:portal_order_update' object.pk %}" class="btn btn-outline-primary"><i class="bi bi-pencil"></i></a>
          <a href="{% url 'orders:portal_order_delete' object.pk %}" class="btn btn-outline-danger"><i class="bi bi-trash3-fill"></i></a>
          {% endif %}
      </td>
  </tr>
  {% endfor %}
</table>


<nav aria-label="Page navigation example">
<ul class="pagination">
{% if page_obj.has_previous %}
<li class="page-item"><a class="page-link" href="?page=1">1</a></li>
<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
{% endif %}
<li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
{% if page_obj.has_next %}
<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">>></a></li>
<li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last</a></li>
{% endif %}
</ul>
</nav>





{% endif %}
{% endblock body %}